import type { Schema } from "../types";

export const schema: Schema = {
  id: "default",
  name: "Schéma cible",
  columns: [
    { key: "job_num_id", label: "job # (id)", required: true },
    { key: "booking_num_id", label: "booking # (id)", required: false },
    { key: "team_num_id", label: "team # (id)", required: false },
    { key: "created_date_time", label: "created date/time", required: false },
    { key: "created_by", label: "created by", required: false },
    { key: "origin_of_request", label: "origin of request", required: false },
    { key: "owner", label: "owner", required: false },
    { key: "assigned_by", label: "assigned by", required: false },
    {
      key: "assigned_by_username",
      label: "assigned by username",
      required: false,
    },
    { key: "job_date", label: "job date", required: false },
    { key: "job_time", label: "job time", required: false },
    {
      key: "expected_start_date",
      label: "expected start date",
      required: false,
    },
    {
      key: "expected_start_time",
      label: "expected start time",
      required: false,
    },
    { key: "expected_end_date", label: "expected end date", required: false },
    { key: "expected_end_time", label: "expected end time", required: false },
    {
      key: "interpreter_arrival_date",
      label: "interpreter arrival date",
      required: false,
    },
    {
      key: "interpreter_arrival_time",
      label: "interpreter arrival time",
      required: false,
    },
    { key: "actual_start_date", label: "actual start date", required: false },
    { key: "actual_start_time", label: "actual start time", required: false },
    { key: "actual_end_date", label: "actual end date", required: false },
    { key: "actual_end_time", label: "actual end time", required: false },
    { key: "time_zone", label: "time zone", required: false },
    {
      key: "interpreter_gender_required",
      label: "interpreter gender required",
      required: false,
    },
    { key: "organization", label: "organization", required: false },
    { key: "customer", label: "customer", required: false },
    {
      key: "customer_accounting_reference",
      label: "customer accounting reference",
      required: false,
    },
    {
      key: "customer_account_executive",
      label: "customer account executive",
      required: false,
    },
    {
      key: "customer_account_manager",
      label: "customer account manager",
      required: false,
    },
    {
      key: "customer_billing_account",
      label: "customer billing account",
      required: false,
    },
    {
      key: "customer_umbrella_number",
      label: "customer umbrella number",
      required: false,
    },
    {
      key: "customer_contract_type",
      label: "customer contract type",
      required: false,
    },
    {
      key: "customer_business_unit",
      label: "customer business unit",
      required: false,
    },
    {
      key: "customer_insurance_type",
      label: "customer insurance type",
      required: false,
    },
    { key: "customer_rate_plan", label: "customer rate plan", required: false },
    {
      key: "billing_organization",
      label: "billing organization",
      required: false,
    },
    { key: "billing_customer", label: "billing customer", required: false },
    {
      key: "billing_customer_accounting_reference",
      label: "billing customer accounting reference",
      required: false,
    },
    {
      key: "billing_customer_account_executive",
      label: "billing customer account executive",
      required: false,
    },
    {
      key: "billing_customer_account_manager",
      label: "billing customer account manager",
      required: false,
    },
    {
      key: "billing_customer_billing_account",
      label: "billing customer billing account",
      required: false,
    },
    {
      key: "billing_customer_umbrella_number",
      label: "billing customer umbrella number",
      required: false,
    },
    {
      key: "billing_customer_contract_type",
      label: "billing customer contract type",
      required: false,
    },
    {
      key: "billing_customer_business_unit",
      label: "billing customer business unit",
      required: false,
    },
    { key: "billable_to", label: "billable to", required: false },
    { key: "client", label: "client", required: false },
    {
      key: "client_accounting_reference",
      label: "client accounting reference",
      required: false,
    },
    { key: "client_category", label: "client category", required: false },
    { key: "client_type", label: "client type", required: false },
    { key: "consumer", label: "consumer", required: false },
    {
      key: "consumer_first_name",
      label: "consumer first name",
      required: false,
    },
    { key: "consumer_last_name", label: "consumer last name", required: false },
    { key: "consumer_email", label: "consumer email", required: false },
    {
      key: "consumer_date_of_birth",
      label: "consumer date of birth",
      required: false,
    },
    {
      key: "consumer_date_of_injury",
      label: "consumer date of injury",
      required: false,
    },
    {
      key: "consumer_record_number",
      label: "consumer record number",
      required: false,
    },
    { key: "consumer_notes", label: "consumer notes", required: false },
    {
      key: "consumer_responsible_payor",
      label: "consumer responsible payor",
      required: false,
    },
    {
      key: "consumer_payor_record_number",
      label: "consumer payor record number",
      required: false,
    },
    {
      key: "consumer_claim_number",
      label: "consumer claim number",
      required: false,
    },
    { key: "number_consumers", label: "number consumers", required: false },
    { key: "location", label: "location", required: false },
    { key: "location_preamble", label: "location preamble", required: false },
    { key: "location_street_1", label: "location street 1", required: false },
    { key: "location_city_town", label: "location city/town", required: false },
    {
      key: "location_state_county",
      label: "location state/county",
      required: false,
    },
    {
      key: "location_zip_postal_code",
      label: "location zip/postal code",
      required: false,
    },
    { key: "location_country", label: "location country", required: false },
    { key: "cost_center", label: "cost center", required: false },
    { key: "cost_center_name", label: "cost center name", required: false },
    { key: "sub_location", label: "sub location", required: false },
    { key: "requested_by", label: "requested by", required: false },
    { key: "requestor_email", label: "requestor email", required: false },
    { key: "venue_information", label: "venue information", required: false },
    { key: "lang_code", label: "lang. code", required: false },
    { key: "language", label: "language", required: false },
    {
      key: "preferred_interpreter",
      label: "preferred interpreter",
      required: false,
    },
    { key: "interpreter_id", label: "interpreter id", required: false },
    { key: "interpreter", label: "interpreter", required: false },
    {
      key: "interpreter_last_name",
      label: "interpreter last name",
      required: false,
    },
    {
      key: "interpreter_first_name",
      label: "interpreter first name",
      required: false,
    },
    { key: "interpreter_status", label: "interpreter status", required: false },
    { key: "interpreter_phone", label: "interpreter phone", required: false },
    { key: "interpreter_email", label: "interpreter email", required: false },
    { key: "interpreter_gender", label: "interpreter gender", required: false },
    {
      key: "interpreter_accounting_reference",
      label: "interpreter accounting reference",
      required: false,
    },
    {
      key: "interpreter_team_if_applicable",
      label: "interpreter team (if applicable)",
      required: false,
    },
    { key: "payment_method", label: "payment method", required: false },
    {
      key: "interpreter_business_unit",
      label: "interpreter business unit",
      required: false,
    },
    {
      key: "interpreter_employment_category",
      label: "interpreter employment category",
      required: false,
    },
    {
      key: "interpreter_rate_plan",
      label: "interpreter rate plan",
      required: false,
    },
    { key: "status", label: "status", required: false },
    { key: "closed_using", label: "closed using", required: false },
    { key: "is_verified", label: "is verified", required: false },
    { key: "cancelled", label: "cancelled", required: false },
    { key: "unmet", label: "unmet", required: false },
    {
      key: "cancellation_reason",
      label: "cancellation reason",
      required: false,
    },
    {
      key: "cancellation_date_time",
      label: "cancellation date time",
      required: false,
    },
    { key: "unfulfilled_reason", label: "unfulfilled reason", required: false },
    {
      key: "unfulfilled_date_time",
      label: "unfulfilled date time",
      required: false,
    },
    { key: "vos_required", label: "vos required", required: false },
    { key: "vos_url", label: "vos url", required: false },
    { key: "secteur_dactivite", label: "Secteur d'activité", required: false },
    {
      key: "num_centre_de_cout_num_budget",
      label: "# Centre de coût / # Budget",
      required: false,
    },
    { key: "sujet", label: "Sujet", required: false },
    {
      key: "nom_personne_rencontree",
      label: "Nom de la personne rencontrée",
      required: false,
    },
    {
      key: "personne_rencontree",
      label: "Personne rencontrée",
      required: false,
    },
    { key: "urgence", label: "Urgence", required: false },
    {
      key: "travel_time_hours_billable",
      label: "Travel Time (Hours)-billable",
      required: false,
    },
    {
      key: "travel_time_hours_payable",
      label: "Travel Time (Hours)-payable",
      required: false,
    },
    {
      key: "clock_hours_billable",
      label: "Clock (Hours)-billable",
      required: false,
    },
    {
      key: "clock_hours_payable",
      label: "Clock (Hours)-payable",
      required: false,
    },
    { key: "mileage_billable", label: "Mileage-billable", required: false },
    { key: "mileage_payable", label: "Mileage-payable", required: false },
    { key: "parking_billable", label: "Parking-billable", required: false },
    { key: "parking_payable", label: "Parking-payable", required: false },
    {
      key: "misc_hours_billable",
      label: "Misc. (Hours)-billable",
      required: false,
    },
    {
      key: "misc_hours_payable",
      label: "Misc. (Hours)-payable",
      required: false,
    },
    {
      key: "meal_break_hours_billable",
      label: "Meal Break (Hours)-billable",
      required: false,
    },
    {
      key: "meal_break_hours_payable",
      label: "Meal Break (Hours)-payable",
      required: false,
    },
    { key: "job_details", label: "job details", required: false },
    {
      key: "appointment_details",
      label: "appointment details",
      required: false,
    },
    { key: "final_job_notes", label: "final job notes", required: false },
    { key: "billing_notes", label: "billing notes", required: false },
    { key: "interpreter_notes", label: "interpreter notes", required: false },
    {
      key: "interpreter_job_notes",
      label: "interpreter job notes",
      required: false,
    },
    { key: "duration_hrs", label: "duration (hrs)", required: false },
    {
      key: "estimated_duration_hrs",
      label: "estimated duration (hrs)",
      required: false,
    },
    { key: "estimated_duration", label: "estimated duration", required: false },
    { key: "mileage", label: "mileage", required: false },
    { key: "booking_mode", label: "booking mode", required: false },
    { key: "open_date_time", label: "open date/time", required: false },
    { key: "offer_date_time", label: "offer date/time", required: false },
    { key: "offer_mode", label: "offer mode", required: false },
    {
      key: "interpreter_assignment_date_time",
      label: "interpreter assignment date time",
      required: false,
    },
    {
      key: "interpreter_confirmed_date_time",
      label: "interpreter confirmed date time",
      required: false,
    },
    { key: "first_offered_date", label: "first offered date", required: false },
    { key: "last_offered_date", label: "last offered date", required: false },
    {
      key: "requestor_confirmed_date_time",
      label: "requestor confirmed date time",
      required: false,
    },
    {
      key: "interpreter_arrival_time_outbound",
      label: "interpreter arrival time outbound",
      required: false,
    },
    {
      key: "interpreter_departure_time_outbound",
      label: "interpreter departure time outbound",
      required: false,
    },
    {
      key: "interpreter_arrival_time_inbound",
      label: "interpreter arrival time inbound",
      required: false,
    },
    {
      key: "interpreter_departure_time_inbound",
      label: "interpreter departure time inbound",
      required: false,
    },
    { key: "invoice_status", label: "invoice status", required: false },
    { key: "invoice_number", label: "invoice number", required: false },
    { key: "invoice_date", label: "invoice date", required: false },
    { key: "receivable_period", label: "receivable - period", required: false },
    {
      key: "receivable_payable_duration_mins",
      label: "receivable - payable duration (mins)",
      required: false,
    },
    {
      key: "receivable_payable_duration_hours",
      label: "receivable - payable duration (hours)",
      required: false,
    },
    {
      key: "receivable_payable_rate",
      label: "receivable - payable rate",
      required: false,
    },
    {
      key: "receivable_total_payable",
      label: "receivable - total payable",
      required: false,
    },
    { key: "r_interpretation", label: "Interpretation", required: false },
    { key: "r_translation", label: "Translation", required: false },
    { key: "r_rush_fee", label: "Rush Fee", required: false },
    { key: "r_cancel_fee", label: "Cancel Fee", required: false },
    { key: "r_mileage", label: "Mileage", required: false },
    { key: "r_travel_misc", label: "Travel (Misc)", required: false },
    { key: "r_taxi", label: "Taxi", required: false },
    { key: "r_hotel", label: "Hotel", required: false },
    { key: "r_parking", label: "Parking", required: false },
    { key: "r_tolls", label: "Tolls", required: false },
    { key: "r_food_and_drink", label: "Food & Drink", required: false },
    { key: "r_miscellaneous", label: "Miscellaneous", required: false },
    { key: "r_tax", label: "Tax", required: false },
    { key: "r_credit", label: "Credit", required: false },
    { key: "r_deduction", label: "Deduction", required: false },
    { key: "r_misc_fee", label: "Misc. Fee", required: false },
    { key: "r_deduction_hours", label: "Deduction (Hours)", required: false },
    { key: "r_misc_hours", label: "Misc. (Hours)", required: false },
    {
      key: "r_travel_time_hours",
      label: "Travel Time (Hours)",
      required: false,
    },
    {
      key: "r_translation_number_of_words",
      label: "Translation (Number of Words)",
      required: false,
    },
    { key: "r_clock_hours", label: "Clock (Hours)", required: false },
    { key: "r_meal_break_hours", label: "Meal Break (Hours)", required: false },
    { key: "r_transportation", label: "Transportation", required: false },
    {
      key: "r_other_not_classified",
      label: "Other (not classified)",
      required: false,
    },
    { key: "payment_status", label: "payment status", required: false },
    { key: "payment_number", label: "payment number", required: false },
    { key: "payable_period", label: "payable - period", required: false },
    {
      key: "payable_payable_duration_mins",
      label: "payable - payable duration (mins)",
      required: false,
    },
    {
      key: "payable_payable_duration_hours",
      label: "payable - payable duration (hours)",
      required: false,
    },
    {
      key: "payable_payable_rate",
      label: "payable - payable rate",
      required: false,
    },
    {
      key: "payable_total_payable",
      label: "payable - total payable",
      required: false,
    },
    { key: "p_interpretation", label: "Interpretation", required: false },
    { key: "p_translation", label: "Translation", required: false },
    { key: "p_rush_fee", label: "Rush Fee", required: false },
    { key: "p_cancel_fee", label: "Cancel Fee", required: false },
    { key: "p_mileage", label: "Mileage", required: false },
    { key: "p_travel_misc", label: "Travel (Misc)", required: false },
    { key: "p_taxi", label: "Taxi", required: false },
    { key: "p_hotel", label: "Hotel", required: false },
    { key: "p_parking", label: "Parking", required: false },
    { key: "p_tolls", label: "Tolls", required: false },
    { key: "p_food_and_drink", label: "Food & Drink", required: false },
    { key: "p_miscellaneous", label: "Miscellaneous", required: false },
    { key: "p_tax", label: "Tax", required: false },
    { key: "p_credit", label: "Credit", required: false },
    { key: "p_deduction", label: "Deduction", required: false },
    { key: "p_misc_fee", label: "Misc. Fee", required: false },
    { key: "p_deduction_hours", label: "Deduction (Hours)", required: false },
    { key: "p_misc_hours", label: "Misc. (Hours)", required: false },
    {
      key: "p_travel_time_hours",
      label: "Travel Time (Hours)",
      required: false,
    },
    {
      key: "p_translation_number_of_words",
      label: "Translation (Number of Words)",
      required: false,
    },
    { key: "p_clock_hours", label: "Clock (Hours)", required: false },
    { key: "p_meal_break_hours", label: "Meal Break (Hours)", required: false },
    { key: "p_transportation", label: "Transportation", required: false },
    {
      key: "p_other_not_classified",
      label: "Other (not classified)",
      required: false,
    },
    {
      key: "place_of_appointment",
      label: "place of appointment",
      required: false,
    },
    {
      key: "internal_special_instructions",
      label: "internal special instructions",
      required: false,
    },
    {
      key: "customer_special_instructions",
      label: "customer special instructions",
      required: false,
    },
    {
      key: "interpreter_special_instructions",
      label: "interpreter special instructions",
      required: false,
    },
    {
      key: "registered_tax_id_description",
      label: "registered tax id description",
      required: false,
    },

    { key: "booking_signer", label: "booking signer", required: false },
  ],
};
